name: Java

on:
  create:
    tags:
      - v*
  workflow_dispatch:
  
jobs:
  jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.0
        with:
          java-version: 11
          distribution: adopt
      
      - name: Add +x permission
        working-directory: java
        run: chmod +x gradlew
      
      - name: Gradle Build
        working-directory: java
        run: ./gradlew clean build
      
      - name: Move app file
        working-directory: java
        run: mv ./build/libs/java*.jar ./app.jar
      
      - name: Upload jar file to Artifact
        uses: actions/upload-artifact@master
        with:
          name: run
          path: ./java/app.jar
          retention-days: 1
          
  qemu-build:
    needs: jar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
     
      - name: Download app from Artifact
        uses: actions/download-artifact@v1
        with:
          name: run
      
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
     
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Move jar file
        run: mv run java/
      
      - working-directory: java
        name: Docker Build
        run: docker buildx build --platform linux/amd64,linux/arm64 -t inerplat/github-action-example:java${{ steps.vars.outputs.tag }} --push .
