name: Java-self

on:
  create:
    tags:
      - v*
  workflow_dispatch:
  
jobs:
  jar:
    runs-on: self-hosted
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2

      - run: |
          download_url="https://cdn.azul.com/zulu-embedded/bin/zulu11.50.19-ca-jdk11.0.12-linux_aarch64.tar.gz"
          wget -O $RUNNER_TEMP/java_package.tar.gz $download_url
      - uses: actions/setup-java@v2
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/java_package.tar.gz
          java-version: '11.0.0'
          architecture: arm64
          
      - name: Add +x permission
        working-directory: java
        run: chmod +x gradlew
      
      - name: Gradle Build
        working-directory: java
        run: ./gradlew clean build
      
      - name: Move app file
        working-directory: java
        run: mv ./build/libs/java*.jar ./app.jar
      
      - name: Upload jar file to Artifact
        uses: actions/upload-artifact@master
        with:
          name: run
          path: ./java/app.jar
          retention-days: 1
          
  qemu-build:
    needs: jar
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
     
      - name: Download app from Artifact
        uses: actions/download-artifact@v1
        with:
          name: run
      
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
     
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Move jar file
        run: mv run java/
      
      - working-directory: java
        name: Docker Build
        run: docker buildx build --platform linux/amd64,linux/arm64 -t inerplat/github-action-example:java${{ steps.vars.outputs.tag }} --push .
